---
abstract: 'Locale::Utils::PlaceholderNamed - Utils to expand named placeholders'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Test::Differences: 0.60
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Utils-PlaceholderNamed
provides:
  Locale::Utils::PlaceholderNamed:
    file: lib/Locale/Utils/PlaceholderNamed.pm
    version: 0.005
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  Moo: 1.003001
  MooX::StrictConstructor: 0
  MooX::Types::MooseLike: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.005
